// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: RobotService.proto
#ifndef GRPC_RobotService_2eproto__INCLUDED
#define GRPC_RobotService_2eproto__INCLUDED

#include "RobotService.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace Robot {

class RobotService final {
 public:
  static constexpr char const* service_full_name() {
    return "Robot.RobotService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status SetLinearSpeed(::grpc::ClientContext* context, const ::Robot::RobotLinearSpeedRequest& request, ::Robot::RobotResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Robot::RobotResponse>> AsyncSetLinearSpeed(::grpc::ClientContext* context, const ::Robot::RobotLinearSpeedRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Robot::RobotResponse>>(AsyncSetLinearSpeedRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Robot::RobotResponse>> PrepareAsyncSetLinearSpeed(::grpc::ClientContext* context, const ::Robot::RobotLinearSpeedRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Robot::RobotResponse>>(PrepareAsyncSetLinearSpeedRaw(context, request, cq));
    }
    virtual ::grpc::Status SetAngularSpeed(::grpc::ClientContext* context, const ::Robot::RobotAngularSpeedRequest& request, ::Robot::RobotResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Robot::RobotResponse>> AsyncSetAngularSpeed(::grpc::ClientContext* context, const ::Robot::RobotAngularSpeedRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Robot::RobotResponse>>(AsyncSetAngularSpeedRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Robot::RobotResponse>> PrepareAsyncSetAngularSpeed(::grpc::ClientContext* context, const ::Robot::RobotAngularSpeedRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Robot::RobotResponse>>(PrepareAsyncSetAngularSpeedRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void SetLinearSpeed(::grpc::ClientContext* context, const ::Robot::RobotLinearSpeedRequest* request, ::Robot::RobotResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void SetLinearSpeed(::grpc::ClientContext* context, const ::Robot::RobotLinearSpeedRequest* request, ::Robot::RobotResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void SetAngularSpeed(::grpc::ClientContext* context, const ::Robot::RobotAngularSpeedRequest* request, ::Robot::RobotResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void SetAngularSpeed(::grpc::ClientContext* context, const ::Robot::RobotAngularSpeedRequest* request, ::Robot::RobotResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::Robot::RobotResponse>* AsyncSetLinearSpeedRaw(::grpc::ClientContext* context, const ::Robot::RobotLinearSpeedRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::Robot::RobotResponse>* PrepareAsyncSetLinearSpeedRaw(::grpc::ClientContext* context, const ::Robot::RobotLinearSpeedRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::Robot::RobotResponse>* AsyncSetAngularSpeedRaw(::grpc::ClientContext* context, const ::Robot::RobotAngularSpeedRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::Robot::RobotResponse>* PrepareAsyncSetAngularSpeedRaw(::grpc::ClientContext* context, const ::Robot::RobotAngularSpeedRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status SetLinearSpeed(::grpc::ClientContext* context, const ::Robot::RobotLinearSpeedRequest& request, ::Robot::RobotResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Robot::RobotResponse>> AsyncSetLinearSpeed(::grpc::ClientContext* context, const ::Robot::RobotLinearSpeedRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Robot::RobotResponse>>(AsyncSetLinearSpeedRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Robot::RobotResponse>> PrepareAsyncSetLinearSpeed(::grpc::ClientContext* context, const ::Robot::RobotLinearSpeedRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Robot::RobotResponse>>(PrepareAsyncSetLinearSpeedRaw(context, request, cq));
    }
    ::grpc::Status SetAngularSpeed(::grpc::ClientContext* context, const ::Robot::RobotAngularSpeedRequest& request, ::Robot::RobotResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Robot::RobotResponse>> AsyncSetAngularSpeed(::grpc::ClientContext* context, const ::Robot::RobotAngularSpeedRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Robot::RobotResponse>>(AsyncSetAngularSpeedRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Robot::RobotResponse>> PrepareAsyncSetAngularSpeed(::grpc::ClientContext* context, const ::Robot::RobotAngularSpeedRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Robot::RobotResponse>>(PrepareAsyncSetAngularSpeedRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void SetLinearSpeed(::grpc::ClientContext* context, const ::Robot::RobotLinearSpeedRequest* request, ::Robot::RobotResponse* response, std::function<void(::grpc::Status)>) override;
      void SetLinearSpeed(::grpc::ClientContext* context, const ::Robot::RobotLinearSpeedRequest* request, ::Robot::RobotResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void SetAngularSpeed(::grpc::ClientContext* context, const ::Robot::RobotAngularSpeedRequest* request, ::Robot::RobotResponse* response, std::function<void(::grpc::Status)>) override;
      void SetAngularSpeed(::grpc::ClientContext* context, const ::Robot::RobotAngularSpeedRequest* request, ::Robot::RobotResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::Robot::RobotResponse>* AsyncSetLinearSpeedRaw(::grpc::ClientContext* context, const ::Robot::RobotLinearSpeedRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::Robot::RobotResponse>* PrepareAsyncSetLinearSpeedRaw(::grpc::ClientContext* context, const ::Robot::RobotLinearSpeedRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::Robot::RobotResponse>* AsyncSetAngularSpeedRaw(::grpc::ClientContext* context, const ::Robot::RobotAngularSpeedRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::Robot::RobotResponse>* PrepareAsyncSetAngularSpeedRaw(::grpc::ClientContext* context, const ::Robot::RobotAngularSpeedRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_SetLinearSpeed_;
    const ::grpc::internal::RpcMethod rpcmethod_SetAngularSpeed_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    Service (const Service &) = delete;
    Service & operator = (const Service &) = delete;
    virtual ~Service();
    virtual ::grpc::Status SetLinearSpeed(::grpc::ServerContext* context, const ::Robot::RobotLinearSpeedRequest* request, ::Robot::RobotResponse* response);
    virtual ::grpc::Status SetAngularSpeed(::grpc::ServerContext* context, const ::Robot::RobotAngularSpeedRequest* request, ::Robot::RobotResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_SetLinearSpeed : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SetLinearSpeed() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_SetLinearSpeed() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetLinearSpeed(::grpc::ServerContext* /*context*/, const ::Robot::RobotLinearSpeedRequest* /*request*/, ::Robot::RobotResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSetLinearSpeed(::grpc::ServerContext* context, ::Robot::RobotLinearSpeedRequest* request, ::grpc::ServerAsyncResponseWriter< ::Robot::RobotResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_SetAngularSpeed : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SetAngularSpeed() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_SetAngularSpeed() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetAngularSpeed(::grpc::ServerContext* /*context*/, const ::Robot::RobotAngularSpeedRequest* /*request*/, ::Robot::RobotResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSetAngularSpeed(::grpc::ServerContext* context, ::Robot::RobotAngularSpeedRequest* request, ::grpc::ServerAsyncResponseWriter< ::Robot::RobotResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_SetLinearSpeed<WithAsyncMethod_SetAngularSpeed<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_SetLinearSpeed : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_SetLinearSpeed() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::Robot::RobotLinearSpeedRequest, ::Robot::RobotResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::Robot::RobotLinearSpeedRequest* request, ::Robot::RobotResponse* response) { return this->SetLinearSpeed(context, request, response); }));}
    void SetMessageAllocatorFor_SetLinearSpeed(
        ::grpc::MessageAllocator< ::Robot::RobotLinearSpeedRequest, ::Robot::RobotResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::Robot::RobotLinearSpeedRequest, ::Robot::RobotResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_SetLinearSpeed() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetLinearSpeed(::grpc::ServerContext* /*context*/, const ::Robot::RobotLinearSpeedRequest* /*request*/, ::Robot::RobotResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SetLinearSpeed(
      ::grpc::CallbackServerContext* /*context*/, const ::Robot::RobotLinearSpeedRequest* /*request*/, ::Robot::RobotResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_SetAngularSpeed : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_SetAngularSpeed() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::Robot::RobotAngularSpeedRequest, ::Robot::RobotResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::Robot::RobotAngularSpeedRequest* request, ::Robot::RobotResponse* response) { return this->SetAngularSpeed(context, request, response); }));}
    void SetMessageAllocatorFor_SetAngularSpeed(
        ::grpc::MessageAllocator< ::Robot::RobotAngularSpeedRequest, ::Robot::RobotResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::Robot::RobotAngularSpeedRequest, ::Robot::RobotResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_SetAngularSpeed() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetAngularSpeed(::grpc::ServerContext* /*context*/, const ::Robot::RobotAngularSpeedRequest* /*request*/, ::Robot::RobotResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SetAngularSpeed(
      ::grpc::CallbackServerContext* /*context*/, const ::Robot::RobotAngularSpeedRequest* /*request*/, ::Robot::RobotResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_SetLinearSpeed<WithCallbackMethod_SetAngularSpeed<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_SetLinearSpeed : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SetLinearSpeed() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_SetLinearSpeed() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetLinearSpeed(::grpc::ServerContext* /*context*/, const ::Robot::RobotLinearSpeedRequest* /*request*/, ::Robot::RobotResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_SetAngularSpeed : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SetAngularSpeed() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_SetAngularSpeed() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetAngularSpeed(::grpc::ServerContext* /*context*/, const ::Robot::RobotAngularSpeedRequest* /*request*/, ::Robot::RobotResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_SetLinearSpeed : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SetLinearSpeed() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_SetLinearSpeed() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetLinearSpeed(::grpc::ServerContext* /*context*/, const ::Robot::RobotLinearSpeedRequest* /*request*/, ::Robot::RobotResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSetLinearSpeed(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_SetAngularSpeed : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SetAngularSpeed() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_SetAngularSpeed() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetAngularSpeed(::grpc::ServerContext* /*context*/, const ::Robot::RobotAngularSpeedRequest* /*request*/, ::Robot::RobotResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSetAngularSpeed(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_SetLinearSpeed : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_SetLinearSpeed() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->SetLinearSpeed(context, request, response); }));
    }
    ~WithRawCallbackMethod_SetLinearSpeed() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetLinearSpeed(::grpc::ServerContext* /*context*/, const ::Robot::RobotLinearSpeedRequest* /*request*/, ::Robot::RobotResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SetLinearSpeed(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_SetAngularSpeed : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_SetAngularSpeed() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->SetAngularSpeed(context, request, response); }));
    }
    ~WithRawCallbackMethod_SetAngularSpeed() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetAngularSpeed(::grpc::ServerContext* /*context*/, const ::Robot::RobotAngularSpeedRequest* /*request*/, ::Robot::RobotResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SetAngularSpeed(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SetLinearSpeed : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_SetLinearSpeed() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::Robot::RobotLinearSpeedRequest, ::Robot::RobotResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::Robot::RobotLinearSpeedRequest, ::Robot::RobotResponse>* streamer) {
                       return this->StreamedSetLinearSpeed(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_SetLinearSpeed() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SetLinearSpeed(::grpc::ServerContext* /*context*/, const ::Robot::RobotLinearSpeedRequest* /*request*/, ::Robot::RobotResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSetLinearSpeed(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::Robot::RobotLinearSpeedRequest,::Robot::RobotResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SetAngularSpeed : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_SetAngularSpeed() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::Robot::RobotAngularSpeedRequest, ::Robot::RobotResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::Robot::RobotAngularSpeedRequest, ::Robot::RobotResponse>* streamer) {
                       return this->StreamedSetAngularSpeed(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_SetAngularSpeed() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SetAngularSpeed(::grpc::ServerContext* /*context*/, const ::Robot::RobotAngularSpeedRequest* /*request*/, ::Robot::RobotResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSetAngularSpeed(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::Robot::RobotAngularSpeedRequest,::Robot::RobotResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_SetLinearSpeed<WithStreamedUnaryMethod_SetAngularSpeed<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_SetLinearSpeed<WithStreamedUnaryMethod_SetAngularSpeed<Service > > StreamedService;
};

}  // namespace Robot


#endif  // GRPC_RobotService_2eproto__INCLUDED
